### PR TITLE
add menu scene; add menubutton script; add tmp

### PR DESCRIPTION
**Pull request by ameijboom**

### CODE REVIEW

**Review by TechnicJelle — CHANGES_REQUESTED** [review]
The functionality is fine, but the UI is not really responsive.
If you could fix that, that might be nice

**Review by TechnicJelle — CHANGES_REQUESTED** [review]
image
I think setting this `Match` to like 0.6 is a better idea

**Comment by ameijboom** [comment]
Should be determined by @cardsforlife91, not a technical detail for this PR imo

**Review by TechnicJelle — APPROVED** [review]
Fine then. If you make sure a designer tweaks this value, then I'll count it as good enough

**Pull request merged**
